name: fibsboard
description: A starting point for Dart libraries or applications.
version: 1.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  dartx: ^1.2.0

dev_dependencies:
  all_lint_rules_community: ^0.0.38
  test: ^1.14.4
